#!/bin/bash
DOTPATH="$(dirname "$(if [[ "$(uname)" == 'Darwin' ]]; then (readlink "$0" || echo "$0"); else readlink -f "$0"; fi)")"
cd "${DOTPATH}"
PIPENV_IGNORE_VIRTUALENVS=1 pipenv run ./devman.py "${@}"
