#!/bin/bash
set -e

DOT="$(dirname "$([[ "$(uname)" == 'Darwin' ]] && realpath "$0" || readlink -f "$0")")"

if [ -e "$HOME/.config/devman/devman.conf" ];
then
  conf="-v $(pwd)/devman.conf:/app/devman.conf:ro"
elif [ -e "$DOT/devman.conf" ]
then
  conf="-v $DOT/devman.conf:/app/devman.conf:ro"
else
  conf=""
fi

if [ -e "$HOME/.config/devman/repos.yaml" ];
then
  repos="-v $(pwd)/repos.yaml:/app/repos.yaml:ro"
elif [ -e "${DOT}/repos.yaml" ];
then
  repos="-v ${DOT}/repos.yaml:/app/repos.yaml:ro"
else
  repos=""
fi

if [ -f $HOME/kronos ]
then
  echo '~/kronos exists as file, please move it using `mv ~/kronos ~/kronos.old`'
  exit 1
elif [ ! -d $HOME/kronos ];
then
  mkdir -p $HOME/kronos
fi

if [ -d $HOME/.ssh/ ];
then
  ssh_conf="-v $HOME/.ssh/:/home/$USER/.ssh/:ro"
fi

if [ -n "$SSH_AUTH_SOCK" ]
then
  ssh_agent="-v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent";
fi

docker run -it --rm \
  -u=$UID:$(id -g $USER) \
  -v /etc/passwd:/etc/passwd:ro \
  -v /etc/group:/etc/group:ro \
  -v $HOME/kronos:/home/$USER/kronos/ \
  $conf \
  $repos \
  $ssh_conf \
  $ssh_agent \
  -it kronostechnologies/devman "$@"
